### ISSUE TITLE
Provide a "NEW queue" page for Laniakea

### ISSUE THREAD

**Issue by jeremiah** [lkhq/laniakea#12]
The current production version of LK has this URL for the new queue: https://master.pureos.net/raw/dak-web/new.html
This looks to be Debian boilerplate. Can we bring that page into LK's git repos and modify it?

**Comment by ximion** [comment]
That's not part of Laniakea ;-)
But the page is still available, at https://master.pureos.net/raw/dak-web/new.html

**Comment by ximion** [comment]
We can only do this properly once Laniakea is able to fully replace dak (in which case it will have its own NEW queue anyway). 
Dak isn't extensible here at all, and there isn't much to replace or integrate, as dak wasn't designed for this. Dak itself generates its new.html page from beautiful string literals ;-) => https://source.puri.sm/pureos/infra/pdak/-/blob/master/dak/queue_report.py

**Comment by jeremiah** [comment]
String literals and embedded HTML. Wow.

**Comment by ximion** [comment]
A product of its times :-)
I do think this will only properly be addressed once Laniakea can handle the archive on its own - drilling into dak to make this work is likely a bad idea, and will break merges with Debian (at the moment I try to keep the delta of Purism's dak to Debian's dak at a minimum).

**Comment by ximion** [comment]
A basic solution exists now for Laniakea's version with native archive support (on the playground server: http://master.scratch.pureos.net/review/ )
Will be expanded on as well in future :-)
