### ISSUE TITLE
Document how to switch a given distro from testing to stable

### ISSUE THREAD

**Issue by jeremiah** [lkhq/laniakea#14]
This is important for derivatives.

**Comment by ximion** [comment]
This is probably out of scope for Laniakea currently - changing a distribution status currently requires changes in many places, including dak and external tooling, and it's an obnoxious process.
I'd rather implement the archive management in Laniakea first, and then make the documentation "run this lk-admin command and be done with it". The point of Laniakea is to *not* have to change configuration in billions of places after all :-)

**Comment by jeremiah** [comment]
Fair point.
