### ISSUE TITLE
Document links 404

### ISSUE THREAD

**Issue by jeremiah** [lkhq/laniakea#15]
On this page: https://laniakea-hq.readthedocs.io/en/latest/general/initial-setup.html this URL 404s; https://github.com/lkorigin/laniakea/blob/master/tests/ci/Dockerfile

Can be found in the "Initial Setup" section.

**Comment by ximion** [comment]
Indeed :-) PRs are welcome ;-)

**Comment by jeremiah** [comment]
Sorry, should've sent this with a PR, but  #16 should fix this #15

**Comment by ximion** [comment]
That initial setup documentation is completely wrong btw ^^ 
Pretty much nothing there is correct anymore, now that Laniakea is Python-only.

**Comment by jeremiah** [comment]
Yes, that I know. :-)
