### ISSUE TITLE
dak email templates need minor editing

### ISSUE THREAD

**Issue by jeremiah** [lkhq/laniakea#17]
Here's what I recently received;
```
tpmfactoryupd_1.1.2529.00-1pureos2.dsc: Refers to non-existing file 'tpmfactoryupd_1.1.2529.00.orig.tar.xz'
Perhaps you need to include the file in your upload?
```
```
If the orig tarball is missing, the -sa flag for dpkg-buildpackage will be your friend.
```
What does the above mean? Does it mean run dpkg-buildpackage with the -sa? dpkg-buildpackage is unhelpful, and example of its manpage;

```
       --as-root
           Only meaningful together with --target (since dpkg 1.15.0).  Requires that the target be run with root rights.

       -si
       -sa
       -sd
       -vversion
       -Cchanges-description
       -m, --release-by=maintainer-address
       -e, --build-by=maintainer-address
```
[This URL](https://www.debian.org/doc/manuals/maint-guide/upload.en.html#option-sa) says 

> When you first upload the package to the archive, you need to include the original orig.tar.gz source, too. If the Debian revision number of this package is neither 1 nor 0, you must provide the dpkg-buildpackage option -sa.

Which is equally mystifying. This is _not_ the first upload and the version is neither 1 or 0, so I use -sa. But what does it *do*? 

> ===
> 
> Please feel free to respond to this email if you don't understand why
> your files were rejected, or if you upload new files which address our
> concerns.

Is the above true in our case? Where does dak@repo.puri.sm go? To whom?

```
r
concerns.
```
This appears to be cruft or a typo.

**Comment by ximion** [comment]
This is resolved with the updates to mailgun - check out the templates at https://github.com/lkhq/laniakea/tree/master/src/mailgun/templates :-)
