### ISSUE TITLE
Buildd fails with tomlkit doesn't have .load method

### ISSUE THREAD

**Issue by jsparber** [lkhq/laniakea#19]
```
meson.build:28:4: ERROR: Problem encountered: Traceback (most recent call last):
  File "/home/julian/purism-code/laniakea/pyreqcheck.py", line 204, in <module>
    sys.exit(run(sys.argv[1:]))
  File "/home/julian/purism-code/laniakea/pyreqcheck.py", line 192, in run
    pyproject = toml.load(f)
AttributeError: module 'tomlkit' has no attribute 'load'
```

I would suggest users not to allow to use `tomllib` or `tomlkit` since it introduces easily errors like this.

**Comment by ximion** [comment]
This is fine with a recent version of Python which has `tomllib`: https://docs.python.org/3.11/library/tomllib.html
The `tomlkit` requirement in the dependency check code was for older Python versions (we need to support at least 3.9), but it looks like the checks on that version weren't quite tight enough.
Thanks for noticing! :-)

**Comment by jsparber** [comment]
Ok good :)

**Comment by ximion** [comment]
I could probably even make this script support `tomli` and `tomli-w`, but I'd much rather only have one TOML module with read/write support to worry about than four of them :-P (they seem to procreate far too quickly)
