### ISSUE TITLE
webswview: Show/Link which binary packages are produced by the source package

### ISSUE THREAD

**Issue by fortysixandtwo** [lkhq/laniakea#23]
The binary package shows a link to its source package:

![phosh-bin](https://github.com/lkhq/laniakea/assets/5196864/b6bf33f2-21a6-45ab-9a06-6436796212df)

But the source package does not show (or maybe I just haven't found it) which binary packages are produced.

![phosh-src](https://github.com/lkhq/laniakea/assets/5196864/4a0c683f-ac78-4269-9835-383a57e7a40d)

Thanks for maintaining laniakea!

**Comment by fortysixandtwo** [comment]
And Build jobs is empty:

![phosh-bin-buildjobs](https://github.com/lkhq/laniakea/assets/5196864/d72a48fa-e7d3-47ff-82cd-9a75513e7256)

**Comment by ximion** [comment]
Yes, that's a missing feature that couldn't be added with the previous dak dependency, but can be easily implemented now.
As far as the build jobs go though, I don't have enough information on why that is (could be that there is simply nothing that needs building).
