### ISSUE TITLE
spears: missing build links to buildd.debian.org

### ISSUE THREAD

**Issue by fortysixandtwo** [lkhq/laniakea#28]
Grepping through the sources I could not find `missing build on` so I assume this comes from britney itself?

![image](https://github.com/lkhq/laniakea/assets/5196864/66d6d5d6-d960-47b3-8846-54d50ef87c01)

Feel free to close if this is not actually an issue with laniakea/spears :)

**Comment by ximion** [comment]
Yeah, that comes from Britney itself, which hardcodes a bunch of Debian stuff. We could potentially postprocess this data and remove it, but that would be quite a hack...
