### ISSUE TITLE
webdash: Pagination links of job queue do not respect show_blocked

### ISSUE THREAD

**Issue by fortysixandtwo** [lkhq/laniakea#29]
When showing pending and blocked jobs (https://master.pureos.net/jobs/queue/1?blocked=true) the pagination links will link to:

- 1: https://master.pureos.net/jobs/queue/1?blocked=
- 2: https://master.pureos.net/jobs/queue/2?blocked=
- Previous (disabled): https://master.pureos.net/jobs/queue/1?blocked=true#
- Next: https://master.pureos.net/jobs/queue/2?blocked=

when on the last (second in my case) page `Next` will link to https://master.pureos.net/jobs/queue/2?blocked=true#

I'm not really familiar with the codebase, but the following code/template (as of a61721a79734e3afb52cb8b6f0d1dac1a09d0628) looks correct to me.

from src/webdash/templates/default/jobs/queue.html:

```
      {% if queue_state != JobQueueState.COMPLETED %}
        <nav class="pagination" role="navigation" aria-label="pagination">
        <a class="pagination-previous"
           href="{{ url_for('jobs.queue', page=current_page-1, blocked='true' if show_blocked else '') if current_page > 1 else '#'}}"
           {{'disabled' if current_page <= 1 }}>
            Previous
        </a>
        <a class="pagination-next"
           href="{{ url_for('jobs.queue', page=current_page+1, blocked='true' if show_blocked else '') if current_page < page_count else '#'}}"
           {{'disabled' if current_page >= page_count }}>
            Next
        </a>

        <ul class="pagination-list">

        {% for i in range(1, page_count + 1) %}
            <li>
            <a class="pagination-link {{'is-current' if i == current_page }}" aria-label="Goto page {{i}}"
               href="{{ url_for('jobs.queue', page=i, blocked='true' if show_blocked else '') }}">{{i}}</a>
            </li>
        {% endfor %}
        </ul>
        </nav>
```

Since that looks fine, I assume the issue is somewhere in `src/webdash/lkweb/jobs/views.py` (?)

**Comment by dos1** [comment]
There was a fix already in #26 when you opened it ;)
