### ISSUE TITLE
lk-admin: Abort if run as root

### ISSUE THREAD

**Issue by agx** [lkhq/laniakea#33]
laniakea installations should use a specific user. Running as root works but triggers problems due to wrong permissions afterwards. So aborting if run as root would make sense to catch this error (e.g. unless overridden via `--force-root` or similar).

**Comment by ximion** [comment]
Way ahead of you :-)
https://github.com/lkhq/laniakea/commit/52c4802ee6fbb13a1373f05e66db41f8706a47dd

Although this will only warn if no sudo is available, maybe this should be a hard error...
How we just cram all of the logic into a daemon and have lk-admin just communicate with that...
