### ISSUE TITLE
Document installation now that LK is pure python

### ISSUE THREAD

**Issue by jeremiah** [lkhq/laniakea#9]
Also, review the install docs for any changes.

**Comment by jeremiah** [comment]
Would be cool to assign me @jeremiah this or be able to assign people. :-)

**Comment by ximion** [comment]
You should have permission to do that now (let me know if you don't) :-)

**Comment by ximion** [comment]
It's done now, but will obviously be extended a lot in the coming weeks: https://laniakea-hq.readthedocs.io/en/latest/general/initial-setup.html :-)
